[global]
server role = standalone server
map to guest = never
log file = /var/log/samba/log.%m

[ebooks]
path = /libraryit/ebooks
valid users = @staff @readonly
read only = no
write list = @staff
[papers]
path = /libraryit/papers
valid users = @staff @readonly
read only = no
write list = @staff
[sourcecode]
path = /libraryit/sourcecode
valid users = @staff
read only = no
write list = @staff
[docs]
path = /libraryit/docs
browseable = yes
read only = no
valid users = contributor librarian
force user = root
create mask = 0777
directory mask = 0777
